#! /usr/local/bin/perl
#
#	Copyright (c) 1992 Bagginses and Company. All Rights Reserved.
#
#	$Id: perlsh,v 1.1 1996-11-11 16:46:19 hayashi Exp $	
#

#push (@INC, '/home/hayashi/bin');
#$readline'rl_NoInitFromFile = 1;
#require 'readline.pl';
use Term::ReadLine;

$rc =  ((getpwuid($<))[7]) . "/.perlshrc";

if (-f $rc)
{
  package main;
  do $rc;
}

package interpreter;

my $term = new Term::ReadLine 'PerlShell';

$PS1 = '> ';
$PS2 = '? ';

sub reader
{
  my ($line, $command);
  $command = '';

  while (1)
  {
    $line = $term->readline($command ? $PS2 : $PS1);
    &quit if (! $line);

    if ($line =~ /\\$/)
    {
      chop $line; $command .= " $line";
    }
    else
    { $command .= " $line"; return $command; }
  }
}

sub evaluator
{ eval ($_[0]); }

sub printer
{
  local (@res) = @_;
  local ($i);
  foreach $i (@res) { print "$i\n"; }
}

sub quit
{ exit (0); }

sub toplevel
{
  local ($command, @result);

  while (1)
  {
    $command = &reader;
    @result = eval ("package main; $command");
    if ($@)
    { print "Error: $@\n" if $@; next; }
    &printer (@result);
  }
}

&toplevel;
