name: test-on-macos
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  make-test:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm-256color

    strategy:
      #fail-fast: false
      matrix:
        # https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners
        os: [macos-latest, macos-13, macos-12]

    name: Build on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install prerequisites
        run: |
            perl -V
            brew install readline
      - name: Run make test
        run: |
            perl Makefile.PL
            make
            make test
